export enum ELessonComplaintStatus {
  PENDING = 'PENDING',
  TUTOR_REVIEW_REQUESTED = 'TUTOR_REVIEW_REQUESTED',
  TUTOR_CONFIRMED = 'TUTOR_CONFIRMED',
  TUTOR_REJECTED = 'TUTOR_REJECTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
